var levels = [
    {
        nodes: 8,
        edges: 20,
        nodeRates: [{
            rate: 20,
            type: hotels[0]
        }, {
            rate: 10,
            type: hotels[1]
        }, {
            rate: 5,
            type: hotels[2]
        }, {
            rate: 10,
            type: shops[0]
        }, {
            rate: 10,
            type: shops[1]
        }, {
            rate: 5,
            type: shops[2]
        }, {
            rate: 5,
            type: treasures[0]
        }, {
            rate: 2,
            type: treasures[1]
        }],
        edgeRates: [{
            rate: 50,
            type: monsters[0]
        }, {
            rate: 30,
            type: monsters[1]
        }, {
            rate: 10,
            type: monsters[2]
        }, {
            rate: 10,
            type: monsters[3]
        }]
    }, {
        nodes: 12,
        edges: 36,
        nodeRates: [{
            rate: 10,
            type: hotels[0]
        }, {
            rate: 10,
            type: hotels[1]
        }, {
            rate: 5,
            type: hotels[2]
        }, {
            rate: 5,
            type: hotels[3]
        }, {
            rate: 2,
            type: hotels[4]
        }, {
            rate: 5,
            type: shops[0]
        }, {
            rate: 5,
            type: shops[1]
        }, {
            rate: 5,
            type: shops[2]
        }, {
            rate: 2,
            type: shops[3]
        }, {
            rate: 2,
            type: shops[4]
        }, {
            rate: 5,
            type: treasures[0]
        }, {
            rate: 3,
            type: treasures[1]
        }, {
            rate: 2,
            type: treasures[2]
        }],
        edgeRates: [{
            rate: 10,
            type: monsters[1]
        }, {
            rate: 20,
            type: monsters[2]
        }, {
            rate: 30,
            type: monsters[3]
        }, {
            rate: 30,
            type: monsters[4]
        }, {
            rate: 10,
            type: monsters[5]
        }]
    }
];